apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vadim-local
patches:
- path: ingress-patch.json
  target:
    group: apps
    kind: Deployment
    name: argo-server
    version: v1
resources:
- ../../base
- ingress.yaml
