apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: cf
  name: rollout-reporter
  namespace: vadim-local
spec:
  eventBusName: codefresh-eventbus
  resource:
    rollouts:
      eventTypes:
      - ADD
      - UPDATE
      - DELETE
      filter:
        createdBy: null
      group: argoproj.io
      namespace: vadim-local
      resource: rollouts
      version: v1alpha1
  template:
    serviceAccountName: rollout-reporter-sa
status: {}
